CREATE TABLE IF NOT EXISTS landing_pages (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    website_id INT UNSIGNED NOT NULL DEFAULT 1,
    slug VARCHAR(160) NOT NULL,
    type ENUM('estimation', 'financement') NOT NULL DEFAULT 'estimation',
    headline VARCHAR(255) NOT NULL,
    sous_titre VARCHAR(255) NOT NULL,
    ville VARCHAR(120) NOT NULL,
    advisor_name VARCHAR(180) NOT NULL DEFAULT '',
    advisor_phone VARCHAR(40) NOT NULL DEFAULT '',
    advisor_zone VARCHAR(255) NOT NULL DEFAULT '',
    advisor_photo_webp VARCHAR(255) NOT NULL DEFAULT '',
    advisor_bio TEXT NULL,
    company_name VARCHAR(180) NOT NULL DEFAULT '',
    legal_url VARCHAR(255) NOT NULL DEFAULT '/mentions-legales',
    privacy_url VARCHAR(255) NOT NULL DEFAULT '/politique-confidentialite',
    review_1_firstname VARCHAR(80) NULL,
    review_1_city VARCHAR(120) NULL,
    review_1_text VARCHAR(255) NULL,
    review_2_firstname VARCHAR(80) NULL,
    review_2_city VARCHAR(120) NULL,
    review_2_text VARCHAR(255) NULL,
    utm_source_default VARCHAR(40) NOT NULL DEFAULT 'google',
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_landing_page_slug (website_id, slug),
    KEY idx_landing_page_active (website_id, active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
