CREATE TABLE IF NOT EXISTS seo_performance_audits (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    perf_score TINYINT UNSIGNED,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
